### PR TITLE
podspec added.

### PR DESCRIPTION
**Pull request by demon1105**

### CODE REVIEW

**Comment by alexbw** [comment]
This already exists here: https://github.com/uservoice/cocoapods-specs/blob/master/Novocaine/0.0.1/Novocaine.podspec

**Comment by alexbw** [comment]
I stopped Cocoa programming before the release of the Cocoapods system. Is it customary for individual repos to host their own podspec?

**Comment by demon1105** [comment]
@alexbw 
Thanks for your reply.
It seems so because most of cocoa developers that I know would like to manage the dependencies by [cocoapods](cocoapods.org).
I believe it'll be much more convenient to use the `novocaine`, if the pull request is merged.

**Comment by alexbw** [comment]
Looks good. Please add "Alex Wiltschko" in the author field, and then I will merge.

**Comment by demon1105** [comment]
@alexbw 
Damn it, it's my fault to forget add your name in it.
Please check it out right now.
:smiley:

**Comment by alexbw** [comment]
Great, thanks!

**Pull request merged**
